//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// KwHg.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x10
#define IDI_ICON1                       17
#define IDD_ABOUTBOX                    19
#define IDS_ABOUTBOX                    20
#define IDD_YOADLLCLIENT_DIALOG         21
#define IDD_TRANSACTION_DIALOG2         22
#define IDD_ORDER_DIALOG                23
#define IDB_LOGO2                       24
#define IDD_CLOCK_DIALOG                25
#define IDD_LOG_DIALOG                  26
#define IDD_STOCKLIST_DIALOG            27
#define IDD_DV_SAVE_DIALOG              28
#define IDD_REGCONF_SAVE_DIALOG         29
#define IDD_KWHG_DIALOG                 30
#define IDB_MATRIX5x7                   31
#define IDD_QTLIST_DIALOG               32
#define IDR_NANUM_GOTHIC_FONT           33
#define IDR_MYFONT                      34
#define IDD_DIALOG_COND_SRCH            35
#define IDD_DIALOG_STKINFO              36
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_STKINFO1                    129
#define IDD_STKINFO2                    131
#define IDD_STKINFO3                    133
#define IDD_STKINFO4                    135
#define IDI_ICON2                       137
#define IDI_ICON3                       138
#define IDR_MENU1                       139
#define IDC_BUTTON_CONNECT              1000
#define IDC_BUTTON_INITIAL              1001
#define IDC_EDIT_LOGIN_ID               1002
#define IDC_EDIT_LOGIN_PWD              1003
#define IDC_EDIT_CERT_PWD               1004
#define IDC_EDIT_SAVE_NM                1005
#define IDC_UpdatePeriod                1006
#define IDC_GRD_STKINFO1                1007
#define IDC_CB_CHART_CN                 1008
#define IDC_BUTTON_ABORT                1009
#define IDC_LIST_ACCOUNTLIST            1010
#define IDC_BUTTON_GO                   1011
#define IDC_LIST_REQUEST_INPUT          1012
#define IDC_STATIC_TIME                 1013
#define IDC_LIST_REQUEST_RESULT         1014
#define IDC_FreezePB                    1015
#define IDC_RADIO_REAL                  1016
#define IDC_RADIO_SIMUL                 1017
#define IDC_LIST_AUTO_INPUT             1018
#define IDC_LIST_REQUEST_RESULT2        1019
#define IDC_BUTTON_REGIST               1020
#define IDC_BUTTON_UNREGIST             1021
#define IDC_LIST_LOG                    1022
#define IDC_BUTTON_GRID_REFRESH         1023
#define IDC_BUTTON_TRLIST               1024
#define IDC_BUTTON_TRLIST2              1025
#define IDC_CHART_STKINFO               1026
#define IDC_BTN_DV2_DEL                 1027
#define IDC_TAB_STKINFO                 1028
#define IDC_BT_QT                       1029
#define IDC_BUTTON_MA5                  1030
#define IDC_TAB_PANEL                   1031
#define IDC_BTN_ALL_READY_BUY           1032
#define IDC_BUTTON_MA10                 1033
#define IDC_BTN_ALL_READY_BUY2          1034
#define IDC_BUTTON_MA20                 1035
#define IDC_BTN_ALL_STOP2               1036
#define IDC_BUTTON_MA60                 1037
#define IDC_BUTTON_F5M_SAVE             1038
#define IDC_DATE_REPEATUNTIL            1039
#define IDC_BTN_ALL_MISS_STOP           1040
#define IDC_BUTTON_GET120               1041
#define IDC_BUTTON_MA120                1042
#define IDC_BTN_ALL_MISS_DEL            1043
#define IDC_BUTTON_MA240                1044
#define IDC_BTN_ALL_MISS_NO             1045
#define IDC_BUTTON_MA480                1046
#define IDC_GRD_STK_LIST                1047
#define IDC_BUTTON_GET_ACCOUNTS         1048
#define IDC_GRD_COND_RSLT_LIST          1049
#define IDC_BT_STKINFO                  1050
#define IDC_GRD_COND_SRCH               1051
#define IDC_GRD_COND_SRCH_LIST          1052
#define IDC_BUTTON_SEARCH               1053
#define IDC_BUTTON_JUMUN                1054
#define IDC_COMBO_SERVER                1055
#define IDC_LIST_CONTICK_HEADER2        1056
#define IDC_LIST_CONTICK2               1057
#define IDC_LIST_DAILY2                 1058
#define IDC_LIST_DAILY_HEADER2          1059
#define IDC_EDIT_1                      1060
#define IDC_EDIT_2                      1061
#define IDC_EDIT_3                      1062
#define IDC_LIST_STOCKLIST              1063
#define IDC_EDIT_4                      1064
#define IDC_LIST_STOCK_SEARCH           1065
#define IDC_EDIT_5                      1066
#define IDC_EDIT_STOCK_SEARCH           1067
#define IDC_EDIT_JONGCODE3              1068
#define IDC_BUTTON_OPEN_TW              1069
#define IDC_BUTTON_DEL_STOCK            1070
#define IDC_STATIC_ACCNAME              1071
#define IDC_BUTTON_GET_STOCK            1072
#define IDC_EDIT_ACC_PWD                1073
#define IDC_EDIT_BUY_AMT1               1074
#define IDC_COMBO_ACC                   1075
#define IDC_EDIT_BUY_AMT2               1076
#define IDC_EDIT_BUY_AMT3               1077
#define IDC_EDIT_BUY_AMT4               1078
#define IDC_EDIT_BUY_AMT5               1079
#define IDC_EDIT_11                     1080
#define IDC_EDIT_12                     1081
#define IDC_EDIT_13                     1082
#define IDC_EDIT_14                     1083
#define IDC_EDIT_15                     1084
#define IDC_EDIT_JUMUN_POSS_AMT         1085
#define IDC_LIST_TARGET                 1086
#define IDC_KHOPENAPICTRL1              1087
#define IDC_STATIC_PROFIT_RATE3         1088
#define IDC_BUTTON_OPEN                 1089
#define IDC_CHECK_ONLYONE               1090
#define IDC_ST_TIME                     1091
#define IDC_LCD_SAMPLE112               1092
#define IDC_CB_ACC                      1093
#define IDC_ST_ACCNAME                  1094
#define IDC_ST_SERVER                   1095
#define IDC_ST_TXT                      1096
#define IDC_ED_JUMUN_POSS_AMT           1097
#define IDC_ED_DV_SUM                   1098
#define IDC_BT_SEARCH                   1099
#define IDC_CK_ONLYONE                  1100
#define IDC_CHK_BUY_LMT_CNT             1101
#define IDC_ED_STOCK_SEARCH             1102
#define IDC_LT_STOCK_SEARCH             1103
#define IDC_BTN_LOG                     1104
#define IDC_BT_STK_SEARCH               1105
#define IDC_BT_GET_STOCK                1106
#define IDC_CST_GRID                    1107
#define IDC_CHART                       1108
#define IDC_ST_STKNM                    1109
#define IDC_ED_OD_AMT                   1110
#define IDC_ED_OD_MNY                   1111
#define IDC_BTN_OD_AMT_ALLSET           1112
#define IDC_CST_GRID2                   1113
#define IDC_ED_CNF_OD_MNY               1114
#define IDC_CST_GRID3                   1115
#define IDC_ED_BUY_LMT_CNT              1116
#define IDC_CB_DVCND1                   1117
#define IDC_CHK_FSTDDY_AT               1118
#define IDC_TAB1                        1119
#define IDC_QT_GRD                      1120
#define IDC_CB_DVCND3                   1121
#define IDC_CB_DV_SET_LST               1122
#define IDC_GET_HTML                    1123
#define IDC_BTN_DV_SET                  1124
#define IDC_GET_DART                    1125
#define IDC_CST_GRID4                   1126
#define IDC_CST_GRID5                   1127
#define IDC_BTN_DEL                     1128
#define IDC_ED_PL_SUM                   1129
#define IDC_BTN_DV_SAVE                 1130
#define IDC_EDIT_DV_SAVE_               1131
#define IDC_ED_CND1_INTV                1132
#define IDC_BTN_DV_GET_SV               1133
#define IDC_BTN_BUY_STOP_Y              1134
#define IDC_BTN_BUY_STOP_N              1135
#define IDC_BTN_AUTOSELL_Y              1136
#define IDC_BTN_AUTOSELL_N              1137
#define IDC_BTN_ALL_SELL                1138
#define IDC_BTN_CHK_SELL                1139
#define IDC_ED_PL_TDSUM                 1140
#define IDC_ST_TXT2                     1141
#define IDC_ST_TXT3                     1142
#define IDC_ED_EX_CNT                   1143
#define IDC_ED_TG_CNT                   1144
#define IDC_CB_SEL_DDY                  1145
#define IDC_ED_SEL_DDY_CP_HH            1146
#define IDC_ED_SEL_DDY_CP_MI            1147
#define IDC_ED_SEL_DDY_CP_SS            1148
#define IDC_BTN_SEL_DDY_CP_SAVE         1149
#define IDC_BTN_REG_SET                 1150
#define IDC_ED_CHK_BUY_LMT_CNT          1151
#define IDC_ED_KS                       1152
#define IDC_ST_TXT4                     1153
#define IDC_ED_KS_MA10                  1154
#define IDC_ED_KQ                       1155
#define IDC_ST_TXT5                     1156
#define IDC_ED_KQ_MA10                  1157
#define IDC_ED_KS_MKT                   1158
#define IDC_ED_KQ_MKT                   1159
#define IDC_CHK_MKT_AT                  1160
#define IDC_BTN_DV_MNY_CAL              1161
#define IDC_BTN_ALL_STOP                1162
#define IDC_BT_CND_SEARCH               1163
#define IDC_QNT_MMT_COMPT               1164
#define IDC_BUTTON_UNIT_TEST            1165
#define IDC_QNT_TOT_COMPT               1166
#define IDC_QNT_QLT_COMPT               1167
#define IDC_BUTTON_LOAD                 1168
#define IDC_CHK_TODAY_READY_ALL_DEL     1169
#define IDC_LIST_FILIST                 1170
#define IDC_GET_DART2                   1171
#define IDC_CHK_HTS_SYNC                1172
#define IDC_CHK_OPBPMT_AT               1173
#define IDC_RADIO_MIS_DEL               1174
#define IDC_CHK_SELDDY_AT               1175
#define IDC_ED_CNF_TPF                  1176
#define IDC_ED_CNF_STL                  1177
#define IDC_ED_CNF_BDV                  1178
#define IDC_COMBO_CNF_SVID              1179
#define IDC_RADIO_MIS_STOP              1180
#define IDC_RADIO_MIS_NO                1181
#define IDC_BTN_RT_SAVE                 1182
#define IDC_RADIO_AG_01                 1183
#define IDC_GRD_STKINFO0                1184
#define IDC_RADIO_AG_02                 1185
#define IDC_CB_DVCND2                   1186
#define IDC_CHK_OD_STP_AT               1187
#define IDC_BUTTON_RTCF                 1188
#define IDC_CUSTOM1                     1189
#define IDC_QNT_VAL_COMPT               1190
#define IDC_ED_RT_LMT_AMT               1191
#define IDC_ED_RT_LMT_STK               1192
#define IDC_ED_RT_TPF                   1193
#define IDC_ED_RT_STL                   1194
#define IDC_ED_RT_BDV                   1195
#define IDC_CB_RT_SVID                  1196
#define IDC_RD_RT_AG_01                 1197
#define IDC_RD_RT_AG_02                 1198
#define IDC_COMBO_CF                    1199
#define IDC_RD_RT_MB_01                 1199
#define IDC_STATIC_LIST1                1200
#define IDC_RD_RT_MB_02                 1200
#define ID_32767                        32767

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         1201
#define _APS_NEXT_SYMED_VALUE           1301
#endif
#endif
